// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKybZWUe75tnjAj__4n7fL2kQkgg9uCg',
    appId: '1:109821855872:web:85d97ba7498933e6493e65',
    messagingSenderId: '109821855872',
    projectId: 'franklin-flow',
    authDomain: 'franklin-flow.firebaseapp.com',
    storageBucket: 'franklin-flow.firebasestorage.app',
    measurementId: 'G-6KCC2032K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARw8uj6js0tLg4s9ssMVCE-2KATqKUkLo',
    appId: '1:109821855872:android:ceda82f6dc03e29e493e65',
    messagingSenderId: '109821855872',
    projectId: 'franklin-flow',
    storageBucket: 'franklin-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpynfdwuJ2hD-1SkcAXeLQOSvxLfwUB30',
    appId: '1:109821855872:ios:eb2a3e84f3da6b3e493e65',
    messagingSenderId: '109821855872',
    projectId: 'franklin-flow',
    storageBucket: 'franklin-flow.firebasestorage.app',
    iosClientId: '109821855872-i95cnhurp0dk5dumu12kanisf8d1bojd.apps.googleusercontent.com',
    iosBundleId: 'com.buelmanager.franklinFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpynfdwuJ2hD-1SkcAXeLQOSvxLfwUB30',
    appId: '1:109821855872:ios:eb2a3e84f3da6b3e493e65',
    messagingSenderId: '109821855872',
    projectId: 'franklin-flow',
    storageBucket: 'franklin-flow.firebasestorage.app',
    iosClientId: '109821855872-i95cnhurp0dk5dumu12kanisf8d1bojd.apps.googleusercontent.com',
    iosBundleId: 'com.buelmanager.franklinFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaKybZWUe75tnjAj__4n7fL2kQkgg9uCg',
    appId: '1:109821855872:web:3110624901a2cdb4493e65',
    messagingSenderId: '109821855872',
    projectId: 'franklin-flow',
    authDomain: 'franklin-flow.firebaseapp.com',
    storageBucket: 'franklin-flow.firebasestorage.app',
    measurementId: 'G-SKB9QD8BDY',
  );

}